# DB config
spring:
  datasource:
    url: jdbc:mysql://118.67.128.116:3306/virusvaccine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234
  sql:
    init:
      data-locations: classpath:db/sql/data.sql
      schema-locations: classpath:db/sql/schema.sql
      mode: always
      continue-on-error: off

