# DB config
spring:
  datasource:
    url: jdbc:mysql://localhost:5000/virusvaccine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234